export const APP_ACTIONS = {
  CHANGE_LOCALE: 'CHANGE_LOCALE',
};

export const SESSION_ACTIONS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
  SET_MESSAGE: 'SET_MESSAGE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
};
